#!/bin/bash
# Author:   Mehmet Ümit Özden
# Website:  http://www.github.com/mehmetumit/k380-swap-keys
# License:  GPLv3
# Description: Simple script for Logitech K380 keyboard to swap upper fn keys

# You can try for other devices too
DEV='K380'
DEST="/etc/udev/rules.d/80-$DEV.rules"
RULE='ACTION=="add", SUBSYSTEM=="hidraw", KERNEL=="hidraw*", SUBSYSTEMS=="hid", KERNELS=="*:046D:B342.*", RUN+="/bin/bash -c \"k380-swap-keys -s\""'

help() {
    cat <<EOF
Usage: k380-swap-keys [OPTIONS...]

Simple script for Logitech K380 keyboard to swap upper fn keys

Options:
	-h		Print this text and exit
	-r		Create rule to automatically swap keys after reconnect device
	-s 		Swap upper fn keys
EOF
}

case "$1" in
	-r) [ "$(id -u)" -eq 0 ] && echo "$RULE" > "$DEST"; printf "Rule created successfully...\nDon't forget to reconnect your device!\n" || echo "You need to run as root!";;
	-s) hid=$(grep -FH "$DEV" /sys/class/hidraw/hidraw*/device/uevent | grep -o "hidraw[[:digit:]]") && [ ! -z "$hid" ] &&  echo -ne "\x10\xff\x0b\x1e\x00\x00\x00" > "/dev/$hid" || echo "Device $DEV not found!";;
	-h|*) help && exit;;
esac

